version: '3.8'

name: menu_app_image
services:
  my_web_app:
    build:
      dockerfile: Dockerfile
    restart: always
    container_name: menuapp-web
    volumes:
      - shared_volume:/menuapp/output
    ports:
      - 8000:80
    env_file:
      - .docker.env
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn menuapp.main:app --host 0.0.0.0 --port 80

  db:
    image: postgres:15.1-alpine
    container_name: menuapp-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - 9000:5432
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 20

  redis:
    image: redis:latest
    container_name: menuapp-cache
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    expose:
      - 6379
    command: redis-server

  celery:
    build:
      dockerfile: celery.Dockerfile
    restart: always
    container_name: menuapp-celery-web
    volumes:
      - shared_volume:/transport/output
    expose:
      - 5672
    command: celery -A transport.main worker --loglevel=INFO --pool=solo

  rabbitmq:
    image: rabbitmq:latest
    container_name: menuapp-rabbitmq
    expose:
      - 5672
      - 15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq


volumes:
  postgres_data:
  shared_volume:
